version: '3'
services:
  price-alert-service:
    build: './price-alert-service'
    ports:
      - "5000:5000"

  alert-service:
    build: './alert-service'
    ports:
      - "7000:7000"

  notice-service:
    build: './notice-service'
    ports:
      - "8000:8000"

  coin-service:
    build: './coin-service'
    ports:
      - "9000:9000"

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - price-alert-service
      - alert-service
      - notice-service
      - coin-service